version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:47"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:17"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security
